spring:
  application:
    name: @artifactId@
  output:
    ansi:
      enabled: ALWAYS

jwt:
  secret: 'blah-blah-secret'
  session-timeout: 60 # seconds

logging:
  pattern:
    dateformat: 'yyyy-MM-dd hh:mm:ss.SSS'
  level:
    root: WARN
    com:
      learn:
        exceptionhandling: INFO

server:
  port: 9090
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER
    include-binding-errors: ON_PARAM
#    whitelabel:
#      enabled: false